### ISSUE TITLE
Timestamp normalization on import

### ISSUE THREAD

**Issue by alfred-landrum** [brimdata/zed#1028]
On import into Brim or zar, we need to ensure records have timestamps that can be interpreted for use during queries, which means that:
* We should ensure that all imported records either have a original timestamp field, or they have an artificial timestamp field with some value (like the time of import), or they are not imported.
* The import & query process need to agree on the range of timestamp values expected & how to interpret them.

**Comment by philrz** [comment]
For a future beyond out-of-the-box Zeek, this also implies letting the user specify what the timestamp field should be. Due to our Zeek heritage, we still have assumptions baked into the software about timestamps always being in a field called `ts`. In a world beyond Zeek, this will not always be the case. Furthermore, there might be multiple fields of type `time` in a particular data source, so a user would need to be given a way to specify which we should use. This dependency would need to ripple through later querying of the data, such that when diverse data sources are sorted & shown together on a timeline, their differing time fields are used simultaneously.

Conclusion: We want time to be the (or a) primary way to partition data, implying its importance to sorting & indexing. So for a given archive, we'd want have some way for a user to identify what should be considered the primary time field. This isn't a problem right now, but will be part of the overall challenge of importing non-Zeek data sources.

**Comment by mccanne** [comment]
No longer relevant with lake model.
