### ISSUE TITLE
windows rename failure in zealot test

### ISSUE THREAD

**Issue by alfred-landrum** [brimdata/zed#1083]
This looks like another kind of Windows related rename issue; the entire error is cut off, but the snippet is:

```
ingest pcap
{
  type: "Error",
  kind: "",
  error: "rename D:\\a\\brim\\brim\\zqd\\sp_1fxMbEVUxkDFgwLLccaSOM68EsD\\.tmp-config.json111630579 D:\\a\\brim\\brim\\zq..."
}
```

https://github.com/brimsec/brim/runs/971541272

**Comment by philrz** [comment]
@alfred-landrum recalls having seen this happening maybe once per week. It was only observed in CI, never locally. He also doesn't recall having seen it happen recently, though we also don't have have ideas of what changes we made that might have fixed it, since it was never linked to any one failing test or code path.

**Comment by nwt** [comment]
Closing since we haven't seen this in over two years.
