### ISSUE TITLE
exclude long running ztests via tags

### ISSUE THREAD

**Issue by alfred-landrum** [brimdata/zed#1657]
We'd like a mechanism that allows excluding some longer-running ztests when running `make test-system`. At a sync meeting, we proposed adding tags in the ztest yaml that could be used for this.

**Comment by philrz** [comment]
It looks like foundation for this work is coming in #1822.

**Comment by philrz** [comment]
Per the last comment above, this support for tagging ztests and invoking them selectively via the environment variable `ZTEST_TAG` was added as part of #1822. The specific tests in that PR that used the technique seem to have since been removed, but the mechanism remains for when it's needed.

Thanks @mattnibs!
