### ISSUE TITLE
implement partials method in dcount aggregator

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#1892]
The `dcount` aggregator currently does not implement partials.  This is easy to remedy as the hyperloglog++ library can merge its internal sketches so we need to merely serialize the sketch in ResultAsPartial() and merge them back together in ConsumeAsPartial().

**Comment by mccanne** [comment]
When this is fixed, please update the caveat in zql/docs/aggregate-functions/README.md regarding countdistinct.

**Comment by philrz** [comment]
Verified in Zed commit 7ea6c59.

Taking a step back, an app-level summary of the user experience of this issue is captured in https://github.com/brimdata/brim/issues/2447#issuecomment-1189520229.  In brief, the issue could be produced in Zed 834a633 by loading the [ZNG zed-sample-data](https://github.com/brimdata/zed-sample-data/tree/main/zng) into a pool and running a query:

```
$ zed query 'from foo | summarize allClientIPCount := dcount(id.orig_h)'
Post "http://localhost:9867/query?ctrl=T": EOF
```

With the panic on stderr for the crashed `zed serve` process:

```
panic: dcount: partials not yet implemented

goroutine 273 [running]:
github.com/brimdata/zed/runtime/expr/agg.(*DCount).ResultAsPartial(0xc0000d1e00, 0x22974a0?)
	/Users/phil/work/zed/runtime/expr/agg/dcount.go:44 +0x27
github.com/brimdata/zed/runtime/op/groupby.(*Aggregator).readTable(0xc0002f07e0, 0x1, 0x1, {0x1cf06d0, 0xc0000c83c0})
	/Users/phil/work/zed/runtime/op/groupby/groupby.go:538 +0x6ca
github.com/brimdata/zed/runtime/op/groupby.(*Aggregator).nextResult(0x0?, 0x0?, {0x1cf06d0?, 0xc0000c83c0?})
	/Users/phil/work/zed/runtime/op/groupby/groupby.go:399 +0x9d
github.com/brimdata/zed/runtime/op/groupby.(*Proc).run.func1(0xc00035a5a0)
	/Users/phil/work/zed/runtime/op/groupby/groupby.go:173 +0x39
github.com/brimdata/zed/runtime/op/groupby.(*Proc).run(0xc00035a5a0)
	/Users/phil/work/zed/runtime/op/groupby/groupby.go:195 +0x132
created by github.com/brimdata/zed/runtime/op/groupby.(*Proc).Pull.func1
	/Users/phil/work/zed/runtime/op/groupby/groupby.go:163 +0x5a
```

Now at Zed commit 7ea6c59 that includes the fix, the query succeeds with no crash.

```
$ zed -version
Version: v1.2.0-6-g7ea6c59b

$ zed query 'from foo | summarize allClientIPCount := dcount(id.orig_h)'
{allClientIPCount:665(uint64)}
```

Thanks @nwt!
