### ISSUE TITLE
filter Keyword  proxied 

### ISSUE THREAD

**Issue by nmweizi** [brimdata/zed#1944]
**Describe the bug**
filter Keyword  proxied "X-FORWARDED-FOR -> 1.1.1.1,53865,1,1.1.1.1"
no result
```
'1.1.1.1' in proxied
proxied=~"*1.1.1.1*"
'*1.1.1.1*' in proxied
``` 

**Desktop Info**
 - OS: MacOS
 - Brim Version [0.21.1]

**Comment by nmweizi** [comment]
Thanks for the explanation

**Comment by philrz** [comment]
Several things have changed since this issue was last reviewed. First, the TZNG format and `bstring` type have both been retired, so here's the test data in modern ZSON format:

```
$ zq -version
Version: v1.2.0-24-gae1ac60a

$ zq -Z repro.zson 
{
    proxied: |[
        "X-FORWARDED-FOR -> 1.1.1.1,53865,1,1.1.1.1"
    ]|
}
```

Since the field ultimately being searched is of `string` type, the [`grep()` function](https://zed.brimdata.io/docs/next/language/functions/grep) is appropriate here.

```
$ zq -Z 'grep("1.1.1.1", proxied)' repro.zson
{
    proxied: |[
        "X-FORWARDED-FOR -> 1.1.1.1,53865,1,1.1.1.1"
    ]|
}
```

The [Search Expressions docs](https://zed.brimdata.io/docs/next/language/overview#7-search-expressions) show more detail on what's possible today. There's still work to be done to make some variations on this search easier to perform. Related issues worth watching include #1428, #2962, and #2250. I'm going to close this specific issue though, since we at least have a way forward on the original problem.
