### ISSUE TITLE
send import status messages only when new chunks written

### ISSUE THREAD

**Issue by alfred-landrum** [brimdata/zed#1980]
When ingesting pcaps to an archive store, we only need to send a `PcapPostStatus` messages right after a new chunk file has been written; the code currently mirrors the file store pcap ingest & sends status messages based on a periodic timer.

**Comment by philrz** [comment]
@jameskerr @mason-fish: I think this issue was only relevant when the backend was outputting partial logs during pcap ingest and notifying the app so it could start displaying some data before all logs had been output. Now the app only shows the logs after Brimcap has completely finished processing the pcap and all logs have been loaded into the pool. If this is how we expect things to remain going forward, I think we could close this issue as a "won't fix". Let me know if you agree.

**Comment by jameskerr** [comment]
Yes, this is how things will be going forward.

**Comment by philrz** [comment]
Thanks @jameskerr. Per prior comment, closing as a "won't fix".
