### ISSUE TITLE
invalid union type output by ZSON writer

### ISSUE THREAD

**Issue by henridf** [brimdata/zed#2050]
```bash
$ echo '{"a": [[], 1]}' | zq -i zson -f zson -
{
    a: [
        [] (0=([null])) (1=((0,int64))),
        1 (1)
    ] (=2)
} (=3)
$ echo '{"a": [[], 1]}' | zq -i zson -f zson - | zq -i zson -t -
/dev/stdin: no such type name: "0"
```
Looks like it's a problem with the ZSON writer given that it is parsed and inferred ok:

```bash
$ echo '{"a": [[], 1]}' | zq -i zson -t - 
#0:record[a:array[union[array[null],int64]]]
0:[[0:[]1:1;]]
```

**Comment by mccanne** [comment]
Interesting.  We need to change the spec to say that decorators are evaluated right to left and change the formatter to output decorators right to left so that types are defined in a top-down order.  This should actually simplify the decorator logic in the zson formatter as this structure previously wasn't quite right...

**Comment by philrz** [comment]
Verified in Zed commit 8824189.

This no longer produces an error.

```
$ echo '{"a": [[], 1]}' | zq -i zson -f zson - | zq -i zson -f tzng -
#0:record[a:array[union[array[null],int64]]]
0:[[0:[]1:1;]]
```

Thanks @nwt!
