### ISSUE TITLE
Remove typed ndjson reader

### ISSUE THREAD

**Issue by henridf** [brimdata/zed#2296]
Once we're satisfied that the new shaper approach has been fully adopted and migrated to, we can:

- remove the typed ndjson reader and associated code (types.json validator, zio/ndjsonio/compat/decoder.go, possibly more)
- remove the zsontypes utility
- (more?)

Filing this as a reminder to do so and assigning to @philrz as he'll surely be the best judge of when the time is right. @philrz, please reassign to me when it's safe to prune this stuff 🙂.

**Comment by philrz** [comment]
The changes in brimdata/brim#1580 also removed the parts of the Brim app that were dependent on this.

**Comment by philrz** [comment]
Verified with Brim commit `19dd931` talking to `zqd` commit `9cdeda8`.

As shown in the attached video, Zeek NDJSON can still be imported into Brim, but the rich typing is no longer applied, which is clear right away from the lack of the stacked bars and the time picker being at January, 1970, which is due to the `ts` field not being stored as a `time` type. The data can still be searched, but if you get into detailed queries, other rough edges become apparent, e.g. IP addresses being stored as strings.

https://user-images.githubusercontent.com/5934157/115420898-607c3180-a1b0-11eb-88f5-d617a73eaada.mp4

Out-of-the-box open source Zeek was the only log format for which we'd ever created this reference typing config, and the rigidity of the approach was part of what motivated us to create the "shaping" approach that's now used instead. The shaper that's functionally equivalent to what was possible with the legacy typing system (but is much more flexible, easier to use, etc.) is at https://github.com/brimdata/zed/blob/main/zeek/shaper.zed. Issue https://github.com/brimdata/zed/issues/2594 tracks the updating of README at https://github.com/brimdata/zed/blob/main/zeek/README.md to describe its use.

At the moment the Brim app doesn't yet provide UX for selecting/applying shapers as logs are being imported, so the best way to make use of shapers is to use them to convert logs to ZNG outside of Brim and then import the ZNG. https://github.com/brimdata/zed/issues/2342 tracks improvements we'll make over time in this area.

Thanks @nwt!
