### ISSUE TITLE
Non-obvious need for quotes in filter

### ISSUE THREAD

**Issue by marktwallace** [brimdata/zed#2301]
We were constructing a zq filter for some zing output, with this example.

The goal was to pick out the rows with name=sp-m1 in this output:

$ zapi -h localhost:9867 ls -l -f zson
{id:"sp_1pLoMhqVe67OmeR1Wk865DrGzM2",name:"files",data_path:"s3://zqd-demo-1/mark/zqd-data-uri/sp_1pLoMhqVe67OmeR1Wk865DrGzM2",storage_kind:"archivestore"}
{id:"sp_1pLcNSzOwCCpVuoHVp741nan8gv",name:"sp-m1",data_path:"s3://brim-scratch/mark/sp-m1",storage_kind:"archivestore"}

I tried what I thought was the obvious filter:

zapi -h localhost:9867 ls -l -f zng | zq -f text "name=sp-m1" -

But it yields no rows. What I had to do was add escaped quotes within the name expression, like this:

$ zapi -h localhost:9867 ls -l -f zng | zq -f text "name=\"sp-m1\"" -
sp_1pLcNSzOwCCpVuoHVp741nan8gv	sp-m1	s3://brim-scratch/mark/sp-m1	archivestore

That worked, but seemed like a really weird requirement. I had to ask Noah for help and even then we took a few tries before we figured it out. You can avoid the escaping by using two kinds of quotes:

zapi -h localhost:9867 ls -l -f zng | zq -f text 'name="sp-m1"' -

I guess I expected it to be more bash-like, and not require quotes unless I had embedded spaces.

**Comment by philrz** [comment]
@marktwallace: I think your issue is similar in spirit to something I encountered yesterday that led me to file #2295. I'm not sure if you got into this level of detail when working with @nwt, but the reason why the quotes were necessary was to prevent `sp-m1` from being interpreted as "an expression that subtracts the value in field `m1` from the value in field `sp`", which is how things work since the search/expr changes landed from #2072. This becomes a little more obvious if you compare the AST representations of each (commit 04d20a8):

```
$ ast 'name=sp-m1'
{
    "op": "SequentialProc",
    "procs": [
        {
            "filter": {
                "lhs": {
                    "name": "name",
                    "op": "Identifier"
                },
                "op": "BinaryExpr",
                "operator": "=",
                "rhs": {
                    "lhs": {
                        "name": "sp",
                        "op": "Identifier"
                    },
                    "op": "BinaryExpr",
                    "operator": "-",
                    "rhs": {
                        "name": "m1",
                        "op": "Identifier"
                    }
                }
            },
            "op": "FilterProc"
        }
    ]
}

$ ast 'name="sp-m1"'
{
    "op": "SequentialProc",
    "procs": [
        {
            "filter": {
                "lhs": {
                    "name": "name",
                    "op": "Identifier"
                },
                "op": "BinaryExpr",
                "operator": "=",
                "rhs": {
                    "op": "Literal",
                    "type": "string",
                    "value": "sp-m1"
                }
            },
            "op": "FilterProc"
        }
    ]
}
```

Of course, looking at the AST can be seen as an unreasonable burden to the user, which is why I made the argument that we maybe try to find a way to make this obvious in the canonical Z. Granted, my argument was said while imagining a Brim app user to whom we could prominently display the canonical Z and hopefully draw their attention to key changes. Since you were working at the command line, you'd unfortunately not have had the benefit of the same. But if we find the canonical Z approach to be helpful in Brim contexts, perhaps we can think of ways to make it more prominent in `zq` use cases also.

I suppose it goes without saying that the changes in #2072 don't necessarily have to stay locked in place indefinitely. The fact that a couple of us have already bumped into these hazards while being normal users of the tech is a little concerning. OTOH depending on how the persona of our target users may evolve over time, perhaps the trickier new behaviors could be seen as justified if they make other operations more intuitive. I'm trying to maintain an open mind at this point.

**Comment by philrz** [comment]
@mccanne was looking more closely at this one. After treating `sp-m1` as a mathematical expression (the value in field `m1` subtracted from the value in field `sp`), the backend will attempt to filter on that result, but a filter only expects a boolean value so it won't match anything. So indeed the current behavior can be framed as a bug.

One way to approach it would be to have the semantic checker determine that the user is attempting a filter on an integer result and inform them that's invalid. That would help the user understand that they truly wanted to do a search on the string `sp-m1` and therefore enclose it in quotes, escape the hyphen, etc. @mccanne also wondered if we could port some of that semantic logic to the app so it could be flagged to the user even earlier, similar to how we want to do things like typeahead & offer auto-completion, highlighting, and so forth.

**Comment by philrz** [comment]
Similar to [#2295](https://github.com/brimdata/zed/issues/2295), it seems we can close this one because the changes in #2692 make it such that quotes are more prevalent in the language and expected in any expression that is not a bare, keyword search. I'll be emphasizing this in the upcoming docs updates.
