### ISSUE TITLE
ZSON for type value is missing parentheses

### ISSUE THREAD

**Issue by nwt** [brimdata/zed#2518]
On branch main at 63c19f71e7afae23254a1eb39db4d1671837c8e6, the type value for field `typ` here is missing parentheses.
```sh
$ go run ./cmd/zq -z - <<<'{typ:({})}'
{typ:{}}
```

**Comment by nwt** [comment]
Update `zson/ztests/primitive-alias.yaml` when fixed.

**Comment by mccanne** [comment]
Hmm.  it seems like the zson type-value parser is messed up.  This is also a strange error...
```
echo "{typ:(int64)}" | zq -z -
{typ:-112125949748}
```
It seems like the the zson parser is encoding the typeval as type int64 but encoding the ZSON type string in zcode.Bytes.

**Comment by philrz** [comment]
Verified in Zed commit 09de9ba.

Revisiting the problem cited in the original issue text, we see the parentheses are now present in the output where they weren't before.

```
$ zq -version
Version: v0.29.0-323-g09de9bab

$ zq -z - <<<'{typ:({})}'
{typ:({})}
```

And for the problem cited further down in a comment, rather than the garbage output that was there before the fix, now the output comes back the same as the input as we'd expect.

```
$ echo "{typ:(int64)}" | zq -z -
{typ:(int64)}
```

Thanks @mccanne!
