### ISSUE TITLE
Abstract the warning channel and create a package for it

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#2600]
@mccanne's proposal at today's group discussion:

> To help understand what's going on in a flowgraph, we should abstract the warning channel that's in proc context and create a package for it. It doesn't have to be complicated initially, but over time it will do more powerful things, such as make it easier to enable different types of warnings. Think of it as being like a logger, but for the warning channel.
> 
> As part of the exercise, we should document the model and settle on the nomenclature for the different classes of error.

Likely an MVP1 target.

**Comment by philrz** [comment]
@mccanne will be doing the first part of this in his hazmat PR.

**Comment by mccanne** [comment]
Async warnings don't work very well.  This mechanism should be replaced by in-line errors throughout the analytics core and compile-time analysis combined with meta-data introspection can catch most of the typos, e.g., your query returns nothing because there is no field `fu` in the lake when you meant to type `foo`.

**Comment by mccanne** [comment]
With new model of explicit missing and embeddeda, warnings are no longer needed.  We will make the UX never when the compile-time analysis can raise problems immediately when it consults the meta-data for optimizations.
