### ISSUE TITLE
out of memory error when fusing many types

### ISSUE THREAD

**Issue by aousterh** [brimdata/zed#2874]
This error occurs with Zed commit [0143b5a](https://github.com/brimdata/zed/commit/0143b5a72c21260fb5ae4e0e96f4c82f178ee977).

The attached [data_4500_types.zson.gz](https://github.com/brimdata/zed/files/6834000/data_4500_types.zson.gz) contains 4500 records, each with its own type. When I try to fuse these into one type, I get an out of memory error:

```
$ zq -version
Version: v0.29.0-413-g0143b5a7

$ zq -o test.zng 'fuse' data_4500_types.zson.gz
fatal error: runtime: out of memory
...
```

Fuse works without error with fewer types:
```
$ zq -z 'head 4000 | fuse | by typeof(this) | count()' data_4500_types.zson.gz
{count:1 (uint64)} (=0)
```

**Comment by nwt** [comment]
Internally, `fuse` relies on `expr/agg.Schema` and `expr.ConstShaper`, which create intermediate types whose number is linear in the number of distinct input record types (`Schema.Mixin` creates one per input type. `ConstShaper.Eval` creates two: one for fill and one for order.) and whose size is linear in the number of distinct field names.

The type context that owns these intermediate types lives almost until `zq` completes, so the values do as well, and they consume substantial memory. `zq -o test.zng fuse data_4500_types.zson.gz` succeeds on my laptop but uses 8 GB of RAM.

I see a few approaches we can take to address this.
1. Use a separate type context and reset it to free intermediate types. I tried this in `expr.createShaper` and found that translating types between type contexts added substantial overhead: running time increased by 33%.
2. Avoid creating intermediate types by operating on `[]zng.Column` instead of *zng.TypeRecord` in `Schema.fuseRecordTypes` and `expr.createShaper`. This isn't a complete solution since nested types can still require creation of intermediate types. It also makes a mess of the code.
3. Rework `zng.Context` so the garbage collector can reclaim unreferenced types. This is a lot of work because it requires moving type IDs out of `zng.Type`.

**Comment by aousterh** [comment]
Why do the intermediate types take up so much space? With 8 GB of RAM and 4500 types, that's 1.78 MB per type for types that only have two fields each, which seems quite high to me.

**Comment by nwt** [comment]
@aousterh: That 8 GB figure includes a lot of uncollected garbage. With [`GOGC=1`](https://pkg.go.dev/runtime#hdr-Environment_Variables) (`GOGC=0` is unusably slow here), it drops to around 5.25 GB.

I did some direct measurement using `runtime.GC` and `runtime.ReadMemStats` and found that `ConstShaper.Eval` creates only one intermediate type (I claimed two above) per input record, each consuming roughly 472 KB. They're as large as they are because each contains all 4501 fields seen in the full input. The `Schema.Mixin` intermediate types average about half of that because the Nth of these types contains all N+1 fields seen in the first N input records.

That works out to 472 KB * 1.5 * 4500 = 3186000 KB, or about 3 GB, and agrees roughly with a heap profile obtained like this.
```
sed -I '' s/allocs/heap/ cli/cli.go
make build
./dist/zq -memprofiile=mem.prof ...
```

Of the remaining 5.25 - 3 = 2.25 GB, I traced 1.5 GB to `expr.ConstShaper.shapers`.

**Comment by aousterh** [comment]
@nwt: The types created during fuse by `Schema.Mixin` make sense to me, and it seems like garbage collection as you suggested in (3) above should address that. I don't understand the types created by `ConstShaper.Eval` though. When reading in the data, one intermediate type should be created per-record, but those types should be small in this example (only 2 fields each). Then, once the fused schema has been created and all records need to be shaped to conform to it, it seems to me that they should be able to reference the one existing type (with N+1 fields). So why does `ConstShaper.Eval` need to create N types, each with N+1 fields?

**Comment by nwt** [comment]
@aousterh: I'm very glad you asked that question! I looked more closely at `expr/shaper.go`, and the short answer is that `ConstShaper.Eval` doesn't need to create those intermediate types.

The long answer is that the `fuse` operator creates a shaper that performs two "transforms"—fill and order. The current code regards those as independent steps and creates an intermediate type to represent the state of a record after filling but before ordering. But of course fill and order aren't really independent steps, and if we modify fill to add fields in the proper sequence, then there's no need for the separate order step (or the intermediate types).

I'm aiming to have that implemented within a few days.

**Comment by aousterh** [comment]
Sounds good to me, thanks for looking into it!

**Comment by nwt** [comment]
With #2897, `zq -o test.zng 'fuse' data_4500_types.zson.gz` uses about 5 GB on my laptop (vs. about 8 GB without it) and completes in about 8 seconds (vs. about 16 seconds without it).

**Comment by nwt** [comment]
With #2897 and #2899, it's down to about 3 GB and 4 seconds on my laptop. A third of that is garbage: Add in `GOGC=25` and it's about 2 GB and 5 seconds.

If we want to take this farther, much of what remains is allocated in `expr.step.append`.

**Comment by philrz** [comment]
Group consensus was we've gone far enough with this for now. Closing.
