### ISSUE TITLE
improve UX of CLI commands so branch knowledge not needed 

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#3022]
With PR #3020, the gentle slope of zed lake commands has been somewhat compromised.  Our goal with branches was that you should be able to use all this stuff without knowing about them. 

However, Phil noted the create-pool / load work flow requires knowledge of `-HEAD` etc...

https://github.com/brimdata/zed/pull/3020#issuecomment-913742524

Also, @nwt and I debated a better name for the `-HEAD` but didn't reach a conclusion.  It should definitely have a better name.

One possibility is having a global branch pointer in $HOME and a local one in $PWD and perhaps setting the global pointer on a create-pool if it doesn't exist.  But this would be a little odd for automation that doens't use checkouts and instead hard codes the branch refs.   If create-pool did this auto-checkout ,then perhaps it could take a flag to not do this...?

**Comment by philrz** [comment]
After having given it more thought, I'd say that most of my reaction was to the inclusion of the `main` portion of `poolname@main` on the `checkout` command line. Since doing a single `checkout` gives the user the benefit of not having to mention the pool name on subsequent `load` and `query` commands, it seems like the expense of requiring the user to type this one extra `checkout` command is minimal compared to show much effort it saves down the road. So if `checkout` was changed to allow the user to say just the pool name and assume branch `main` in that case, I think it would address most of my concern.

The question of how/where state gets persisted is still fuzzy in my mind. For this more entry-level user that may want to remain blissfully unaware of the role of branches, something in `$HOME` or otherwise globally-persisted does feel appropriate. I'm imagining use cases where a user executes `cd` at the shell to move to various locations on their filesystem as they find files they want to incrementally `load` to an existing pool, hence they'd want their current `checkout` setting to persist. Similarly they might have files spread out across their filesystem that they want to compare next to `query` outputs (e.g., via `diff`), so they might `cd` to different locations for that as well. It's for this reason that I'd be nervous about only tying state to a specific non-global location on the filesystem.

**Comment by philrz** [comment]
Verified in Zed commit f5fef7c.

The linked PR took the approach of reintroducing the `-p` option for just the `zed lake checkout` command (name subject to change per #3025). This allows the user to make a one-time reference to just the pool name and then be effectively working on the `main` branch of that pool for all subsequent commands like `load` and `query`.

For example, using with the [Zeek TSV zed-sample-data](https://github.com/brimdata/zed-sample-data/tree/main/zeek-default) as input:

```
$ zed -version
Version: v0.29.0-504-gf5fef7c0

$ zed lake init
using environment variable ZED_LAKE_ROOT
lake created: /Users/phil/logs

$ zed lake create logs
pool created: logs 1xp4Jy0piadkETlMBZ4aZm1vrxn

$ zed lake checkout -p logs
Switched to branch "main" on pool "logs"

$ zed lake load *
1xp4MGZxE1nWcn9fBqFmuhWDOmY committed

$ zed lake query 'count() by _path | sort -r'
{_path:"conn",count:1021952(uint64)}
{_path:"files",count:162986(uint64)}
{_path:"http",count:144034(uint64)}
...
```

While this should be suitable to users that aren't yet ready to learn the full capabilities of branches, the mention of "main" in the output of `checkout` might serve to tug them along on the "gentle slope" and review the CLI help and/or design doc to see what else is possible.

Thanks @mccanne!
