### ISSUE TITLE
integrations docs

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#3152]
We should create a new landing zone for docs that describe integration and kick off our "integrations" with Kafka and Logstash as we have issue #3151 describing logstash and the zinger work to support kafka.

**Comment by philrz** [comment]
I'm going to close this one because we do indeed now have an "Integrations" section in the docs site. Right now it's populated with content for Amazon S3, Auth0, and Zeek, but is ready to be expanded to include things like zync, Brimcap, Logstash, Fluentd, etc. as we have time & user demand justifies it.

![image](https://github.com/brimdata/zed/assets/5934157/5bd9a095-fc6b-4210-aba0-91095eb11ae8)
