### ISSUE TITLE
zapi load behavior on input error

### ISSUE THREAD

**Issue by nwt** [brimdata/zed#3274]
As https://github.com/brimdata/zed/issues/3271#issuecomment-967121019 points out, `zapi load` creates a commit if it encounters an input error after successfully reading at least one input value. It should either not create the commit or have an option not to create it.

**Comment by philrz** [comment]
I've verified this one is no longer a problem.

Here's a repro from back on Zed commit 3aceae3 around when this issue was filed. With a `zed lake serve` serving a fresh lake, we see that `zapi load` accepts the good data into a successful commit and quietly drops the rest, which reflects the original bug report.

```
$ cat good_input_1.zson 
{say:"hello"}

$ cat bad_input.zson 
{bad_input}

$ cat good_input_2.zson 
{say:"goodbye"}

$ zapi -version
Version: v0.32.0-18-g3aceae3f

$ zapi create bug
pool created: bug 2CXYebBOLyAXNsxfSQY3T122O6M

$ zapi use bug@main
Switched to branch "main"

$ cat good_input_1.zson bad_input.zson good_input_2.zson | zapi load -
2CXYfq8ybwoThCtyt23wyGKklhp committed

$ zapi log
commit 2CXYfq8ybwoThCtyt23wyGKklhp (HEAD -> main)
Author: phil@Phils-Mac.local
Date:   2022-07-27T19:35:02Z

    loaded 1 data object

    2CXYfuVGLKNa7R1Y7Su8wD8vm1I 1 record in 16 data bytes

$ zapi query -z 'count()'
{count:1(uint64)}
```

Now with current Zed commit 26dbda0, we have the desired behavior where the error is shown for the bad input and no commit succeeds.

```
$ zed -version
Version: v1.2.0-20-g26dbda03

$ zed create bug
pool created: bug 2CXZ1qASPBmkBnQgJzcVJt8pg7F

$ zed use bug@main
Switched to branch "main" on pool "bug"

$ cat good_input_1.zson bad_input.zson good_input_2.zson | zed load -
(0/1) 42B 42B/s
Post "http://localhost:9867/pool/2CXZ1qASPBmkBnQgJzcVJt8pg7F/branch/main": parse error: no type name found for field "bad_input"

$ zed log
status code 500: unknown pool metadata type: "log"
```

That last error message is a symptom of known bug #3029, but is indicative of an empty pool, which is what we want.

We find the same is true even if a large amount of data is seen by `zed load` before encountering the bad input. For instance, if we attempt to load all of the [ZSON zed-sample-data](https://github.com/brimdata/zed-sample-data/tree/main/zson) with the bad input tacked on at the very end.

```
$ gzcat ~/work/zed-sample-data/zson/* | cat - bad_input.zson | zed load -
(0/1) 1.06GB 15.81MB/s
Post "http://localhost:9867/pool/2CXZ1qASPBmkBnQgJzcVJt8pg7F/branch/main": parse error: no type name found for field "bad_input"

$ zed log
status code 500: unknown pool metadata type: "log"
```

Closing as fixed.
