### ISSUE TITLE
Write up: migrations from zng2021 data lakes

### ISSUE THREAD

**Issue by mattnibs** [brimdata/zed#3634]
Create a tutorial for migrating old zng2021 lakes specifically from Brim.

**Comment by nwt** [comment]
I think this script will work for most folks though the paths might not be right on Windows.

```sh
#!/bin/sh

case $(uname -s) in
    Darwin )
        PATH=/Applications/Brim.app/Contents/Resources/app.asar.unpacked/zdeps:$PATH
        brim_dir="$HOME/Library/Application Support/Brim"
        ;;
    Linux )
        PATH=/opt/Brim/resources/app.asar.unpacked/zdeps:$PATH
        brim_dir=$HOME/.config/Brim
        ;;
    * ) # Windows
        PATH=$HOME/AppData/Local/Programs/Brim/resources/app.asar.unpacked/zdeps:$PATH
        brim_dir=$HOME/AppData/Roaming/Brim
        ;;
esac

if [ $# -gt 1 ]; then
     echo "usage: $0 [BRIM_DATA_DIR]" >&2
     exit 1
elif [ $# = 1 ]; then
    brim_dir=$1
fi

set -e

echo "migrating lake at '$brim_dir/data/lake' to '$brim_dir/lake'"
cd "$brim_dir"

# Sort these by decreasing modification time so we can use
# 'entry.id==... | head 1 | yield entry.name' below to determine current
# pool names.  (We can't use entry.ts for that because it reflects pool
# creation time rather than modification time.)
pools_zngs=$(ls -t data/lake/pools/*.zng)

export ZED_LAKE=$PWD/lake
if [ -e "$ZED_LAKE" ]; then
    if ! stderr=$(zed ls 2>&1 >/dev/null); then
        exec "fatal error: 'zed ls' failed with this output: '$stderr'" >&2
        exit 1
    fi
else
    zed init
fi

ksuid_glob='???????????????????????????'
for pool_dir in data/lake/$ksuid_glob; do
    pool_ksuid=${pool_dir##*/}
    pool_name=$(zq -f text "entry.id==ksuid('$pool_ksuid') | head 1 | yield entry.name" $pools_zngs)

    branch_count=$(zq -f text 'yield entry.name | sort | uniq | count()' $pool_dir/branches/*.zng)
    if [ "$branch_count" != 1 ]; then
        # Handling multiple branches without zed v0.33.0 is impractical.
        echo "skipping '$pool_name' ($pool_ksuid): found multiple ($branch_count) branches"
        continue
    fi

    if zed ls "$pool_name" >/dev/null 2>&1; then
        echo "skipping '$pool_name' ($pool_ksuid): pool name already exists in '$ZED_LAKE'"
        continue
    fi

    echo "migrating '$pool_name' ($pool_ksuid)"
    zed create -q -orderby ts:desc "$pool_name"
    zed load -q -use "$pool_name"@main $pool_dir/data/$ksuid_glob.zng
done
```

**Comment by jameskerr** [comment]
@nwt I ran this migration script when I had the 4BG demo.pcap loaded and got this error.

<img width="811" alt="Screen Shot 2022-03-22 at 5 21 18 PM" src="https://user-images.githubusercontent.com/3460638/159597978-7ca89427-ec5e-44db-8219-b7dd9dcef048.png">

**Comment by nwt** [comment]
@jameskerr: Fixed in #3738.

**Comment by philrz** [comment]
I take it the assumption is that it's a prerequisite that Windows users would have a Unix-style shell available to run this script? If so, indeed, the paths are probably not right since in my experience it'll depend on what you're relying on to provide your shell, e.g., in Cygwin it looks like you'd use `$HOMEPATH` (which resolves to `\Users\$USERNAME`) instead of `$HOME` (which resolves to `/home/$USERNAME`, which is a directory inside Cygwin's little universe and not below the necessary Windows directories like `AppData`).

What's the intended audience for this script? If it's intended for use by hackers, giving them a Unix-style script and leaving it up to them to figure out how to adapt it to their choice of Unix overlay might be reasonable. OTOH if it's intended to be user-friendly to typical Windows users that aren't generally expected to have Unix tooling, it'd seem that offering a .BAT or PowerShell variant would be the way to go. I'm guessing the core Brim Dev team would not be thrilled at writing and testing such a thing, but I might be game to take it on if there's interest. Let me know.

**Comment by jameskerr** [comment]
Yeah we're are trying to provide a script to migrate users to the new lake format. Any efforts to make that easier for users is welcome @philrz 

The lake used to be in data/lake and now it's in lake/

**Comment by philrz** [comment]
Since that fix to [#3738](https://github.com/brimdata/zed/pull/3738) referenced landed yesterday, this morning I tested out the migration script on macOS using last night's nightly build [https://storage.googleapis.com/brimsec-releases/brim/v0.30.0-prerelease-f4152a70.0/macos/Brim-0.30.0-prerelease-f4152a70.0.dmg](https://storage.googleapis.com/brimsec-releases/brim/v0.30.0-prerelease-f4152a70.0/macos/Brim-0.30.0-prerelease-f4152a70.0.dmg) and it was a success. Specifically:

1.  I had a GA `v0.28.0` install with two existing pools
2.  I quit the app and installed the new version
3.  When the new Brim launched, I saw that the pools list was empty
4.  I ran the migrate script from the shell
      ```
      $ ./migrate.sh 
      migrating lake at '/Users/phil/Library/Application Support/Brim/data/lake' to '/Users/phil/Library/Application Support/Brim/lake'
      migrating 'wrccdc.pcap' (26q1Gy9ytPtiFCtHJ9Nl1n9z5JH)
      migrating 'zeek-default' (26q1IpAp5vHgx1bOP9yAz7CJRNk)
      ```
5.  I clicked **View > Reload** in Brim and now both pools appeared and I was able to click on them and use them

That all seemed good to me. Since I've now witnessed the logic doing its thing in the Unix realm, next I'll take a shot at seeing if I can cook up something functionally equivalent in .BAT/PowerShell.

**Comment by nwt** [comment]
@philrz: I've modified the script to use `APPDATA` and `LOCALAPPDATA` instead of `HOME` on Windows and to avoid `PWD`, so it now works with pretty much any Windows `sh` variant. I've tested it with BusyBox, Cygwin, and MSYS2.

**Comment by nwt** [comment]
(BusyBox is nice because it doesn't have an installer. You just download https://frippery.org/files/busybox/busybox.exe and run it.)

**Comment by philrz** [comment]
@nwt: Ah, cool! I was familiar with BusyBox from other contexts but hadn't realized it had gotten that easy on Windows. I just tried my hand at making those env var changes and witnessed the script now working on Windows with BusyBox, so :+1: there.

Is the plan to basically point users at this script via some article and say "If you still want your old data, run this script"? If so, then it does indeed seem that saying it'll work with BusyBox, Cygwin, or MSYS2 (and showing how easy it is to download & use BusyBox if a user is Unix ignorant) might be plenty good. I was still game to try my hand at writing something in PowerShell just because it seemed like it might be a fun dorky nerd project (at least, until it becomes un-fun, which it might). If there was a desire to actually have the script be something automatically run upon first launch after upgrading Brim, then it would seem all the more justified to have a Windows native variant of the script, since I assume you'd not be shipping BusyBox with the app. But if you all aren't interested in having a parallel implementation of the logic lying around that would need to be tested/etc. and hence wouldn't really want the PowerShell one, I'd not spend the time. Please do let me know what you think.

**Comment by jameskerr** [comment]
@philrz The plan is make the first heading in the release notes be "Where did my pools go?" The release notes will pop up when the user downloads the new version. Then explain the new lake format and link to the article detailing how to migrate. That article will include this script. I am writing the article today and will keep you posted.

We are not going to automatically migrate like we've done in the past.

**Comment by jameskerr** [comment]
I've verified that the fix worked for my data @nwt . Thanks!
