### ISSUE TITLE
Split output on size threshold

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#3955]
As requested by a community user in a [Slack thread](https://brimdata.slack.com/archives/CTSMAK6G7/p1654696247596769):

> Does anyone have any recommendations for chunking large ZNG files outside of pushing to a Zed lake? We have some edge compute cases where we'd like to take very large ZNG files (sometimes in the 10s if not 100 of GBs each) and do some ZQ CLI processing on them and other processes we have with Go and Python libraries. The issue is the ZNG files often are too large to load into memory for some of what we do. My thought was if there was a way to chunk out the file into smaller files, we could work in memory of these remote systems and do some pre-processing before the data is returned to our infrastructure.
If there is nothing in Zed query itself, do you think there would be data corruption issues if we used something like `split`? Something like `split -b 1000k --additional-suffix=.zng largefile.zng smallfileprefix`

**Comment by nwt** [comment]
> Something like `split -b 1000k --additional-suffix=.zng largefile.zng smallfileprefix`

Here's a roughly equivalent `zq` command using the `-splitsize` flag from #3957.
```
zq -split . -splitsize 1000KiB -o smallfileprefix largefile.zng
```
 (It's only roughly equivalent because, while `split -b 1000k` will create files that are exactly 1,024,000 bytes, `zq -split . -splitsize 1000KiB` will create files that are at least that long but almost always longer. This happens both because `zq` won't split a value across two files and—for binary formats like Parquet and ZNG—because of buffering in the underlying encoder.)
