### ISSUE TITLE
Using the cast function to convert ip types does not work

### ISSUE THREAD

**Issue by burpheart** [brimdata/zed#4314]
I have some string type IP addresses stored in a json.
I want to use the cast function to force a string to be converted to an ip type and then use cidr_match to match the ip address.
But I found that it doesn't work. The converted type is still a string which can't be handled by cidr_match.

```
{"ipaddr":"10.0.0.1","data":"test1"}
{"ipaddr":"10.0.0.2","data":"test2"}
{"ipaddr":"192.168.2.1","data":"test3"}



typeof(cast(ipaddr,<[ip]>))
----------
"<string>"
"<string>"
"<string>"

where cidr_match(10.0.0.0/8,cast(host,<[ip]>))
----------
nil

```

**Comment by philrz** [comment]
@burpheart: It's not working because the expression of the type in that `cast()` call reflects an attempt to cast to an _array of `ip`_, not a primitive `ip` type. We can see it working if we drop the square brackets. Note how the quotes are gone in `real_ip`, which is a visual indicator the cast was successful.

```
$ zq -z 'real_ip:=cast(ipaddr,<ip>)' data.json 
{ipaddr:"10.0.0.1",data:"test1",real_ip:10.0.0.1}
{ipaddr:"10.0.0.2",data:"test2",real_ip:10.0.0.2}
{ipaddr:"192.168.2.1",data:"test3",real_ip:192.168.2.1}

$ zq -z 'where cidr_match(10.0.0.0/8,cast(ipaddr,<ip>))' data.json 
{ipaddr:"10.0.0.1",data:"test1"}
{ipaddr:"10.0.0.2",data:"test2"}
```

BTW, for this type of simple cast you can also use the shorthand:

```
$ zq -z 'where cidr_match(10.0.0.0/8,ip(ipaddr))' data.json 
{ipaddr:"10.0.0.1",data:"test1"}
{ipaddr:"10.0.0.2",data:"test2"}
```

Were there docs you were working from that led you to believe the syntax with the square brackets was necessary? If you could point them out I'd look at getting those updated to be clearer.
