### ISSUE TITLE
fall back to original data on error reading commit or journal cache object

### ISSUE THREAD

**Issue by nwt** [brimdata/zed#4328]
An error in lake/commits.Store.getSnapshot or lake/journal.Store.getSnapshot is unrecoverable even though those methods read objects containing only cached information. (We've seen a lake rendered inaccessible by a corrupt journal snap.zng.) We should change those methods to log the error and then fall back to reading the original data.

**Comment by philrz** [comment]
For archival purposes, the zync community user's specific error situation was that they'd upgraded Zed from `v1.2.0` to `v1.4.0` and then found when doing `zed ls` they saw the error message:

```
status code 500: zngio: encountered wrong version bit in framing
```

In that specific case they were able to get working again by just deleting the `snap.zng` which was safe to do since it was just a cache file.

**Comment by philrz** [comment]
The community zync user that originally reported the problem was helpfully able to provide some tips on how to repro the problem and we've successfully followed them. Here's reliable repro steps with Zed commit 9350b5a.

1. Start a fresh Zed service.

```
$ zed -version
Version: v1.5.0-22-g9350b5a9

$ rm -rf lake && zed -lake lake serve
{"level":"info","ts":1676050752.1012402,"logger":"core","msg":"Started"}
{"level":"info","ts":1676050752.10148,"logger":"httpd","msg":"Listening","addr":"[::]:9867"}
...
```

2. In one shell, start a tight loop of `zed ls`.

```
$ while true; do zed ls; done
```

3. In another shell, run the following script to rapidly make pools.

```
$ cat mkpools.sh 
#!/bin/sh
NUM=1
while [ "$NUM" -lt 800 ]; do
  zed create -orderby kafka.offset:asc pool${NUM}
  NUM=$(expr $NUM + 1)
done

$ ./mkpools.sh 
pool created: pool1 2LYb8Lke9VinfdbwHztifG62Ftm
pool created: pool2 2LYb8MHTuxAPKYUmQ97WVmK8SFB
....
pool created: pool99 2LYb8m6oDpXhy8vK0GH4RQPo6B3
pool created: pool100 2LYb8heI6h0Merim14madLLq33Y
status code 500: malformed zng record
status code 500: malformed zng record
```

I've found that if the `zed ls` loop is _not_ running, the 800 pools can be created without issue. However, at that point if I start the `zed ls` loop and drop them just as rapidly with the following script, I can once again corrupt it.

```
$ cat rmpools.sh 
#!/bin/sh
NUM=1
while [ "$NUM" -lt 800 ]; do
  echo y | zed drop pool${NUM}
  NUM=$(expr $NUM + 1)
done

$ ./rmpools.sh 
Are you sure you want to delete pool "pool1"? There is no going back... [y|n]
pool deleted: pool1
Are you sure you want to delete pool "pool2"? There is no going back... [y|n]
pool deleted: pool2
...
Are you sure you want to delete pool "pool49"? There is no going back... [y|n]
pool deleted: pool49
status code 500: truncated input
status code 500: truncated input
status code 500: truncated input
```

**Comment by philrz** [comment]
I've verified in Zed commit 11ad2bd using the repro steps above that I can now successfully execute the `mkpools.sh` and then `rmpools.sh` scripts while the looping `zed ls` is running during both.

The linked PR mentions that the kinds of errors that used to corrupt the lake now are logged and operations continue. Therefore I kept the `zed serve` output during the run and have attached it here as [zed.log.gz](https://github.com/brimdata/zed/files/10842127/zed.log.gz). Here's a summary of the error messages:

```
$ zq -Z 'level=="error" | count() by error | sort -r' zed.log.gz 
{
    error: "truncated input",
    count: 228 (uint64)
}
{
    error: "unknown ZNG message frame type: 3",
    count: 158 (uint64)
}
{
    error: "malformed zng record",
    count: 156 (uint64)
}
{
    error: "zngio: encountered wrong version bit in framing",
    count: 96 (uint64)
}
{
    error: "large value of 383934126340 bytes exceeds maximum read buffer",
    count: 21 (uint64)
}
{
    error: "zngio: lz4: invalid source or destination buffer too short",
    count: 2 (uint64)
}
```

I'll bring these to the attention of the Dev team to make sure there's no surprises here. But since the lake corruption no longer seems to be occurring, I'm assuming we're 👍 here.

Thanks @nwt!
