### ISSUE TITLE
Document top operator

### ISSUE THREAD

**Issue by nwt** [brimdata/zed#4590]
There's no documentation for the top operator, but there should be.

**Comment by philrz** [comment]
We had some internal discussion about this one. I'd intentionally been holding off on documenting it because the word `top` is used differently in some adjacent tools when compared to the `top` operator we've currently got, and I was hoping to resolve that before we reveal it to users.

To summarize, Zed's is currently "show me the values with the uppermost value of the referenced field", e.g., using a Zeek example, the 5 connections with the most `orig_bytes`:

```
$ zq -f table 'top 5 orig_bytes' conn.log.gz
_path ts                          uid                id.orig_h    id.orig_p id.resp_h    id.resp_p proto service duration    orig_bytes resp_bytes conn_state local_orig local_resp missed_bytes history          orig_pkts orig_ip_bytes resp_pkts resp_ip_bytes tunnel_parents
conn  2018-03-24T17:33:05.415532Z Cy3R5w2pfv8oSEpa2j 10.47.8.19   49376     10.128.0.214 443       tcp   -       202.457994  4862366    1614249    S1         -          -          0            ShAdtttDTaTTTt   7280      10015980      6077      3453020       -
conn  2018-03-24T17:15:20.705347Z CWtQuI2IMNyE1pX47j 10.47.6.161  52121     134.71.3.17  443       tcp   -       1269.320626 2267243    54791018   OTH        -          -          0            DTadtATttTtTtT   152819    10575303      158738    113518994     -
conn  2018-03-24T17:25:15.208232Z CVimRo24ubbKqFvNu7 172.30.255.1 11        10.128.0.207 0         icmp  -       100.721937  1647088    0          OTH        -          -          0            -                44136     2882896       0         0             -
conn  2018-03-24T17:15:20.630818Z CO0MhB2NCc08xWaly8 10.47.1.154  49814     134.71.3.17  443       tcp   -       1269.512465 1618740    12880888   OTH        -          -          0            ^dtADTatTtTtTtT  110169    7594230       111445    29872050      -
conn  2018-03-24T17:15:20.637761Z Cmgywj2O8KZAHHjddb 10.47.1.154  49582     134.71.3.17  443       tcp   -       1266.367457 1594682    53255700   OTH        -          -          0            ^dtADTatTtTtTtTW 131516    8407458       142488    110641641     -
```

Whereas in some other tools it's "show me the most common values for the field(s)", e.g., in [Splunk](https://docs.splunk.com/Documentation/Splunk/8.0.4/SearchReference/Top):

![image](https://github.com/brimdata/zed/assets/5934157/78c63f8b-8ae4-4313-bbf4-9b919ae9e6fa)

And if we'd wanted to implement that in Zed, it could use the current `top`:

```
$ zq -f table 'count() by name | top 5 count' weird.log.gz
name                             count
bad_HTTP_request                 11777
line_terminated_with_single_CR   11734
unknown_HTTP_method              140
above_hole_data_without_any_acks 107
active_connection_reuse          72
```

Across all these, combining `sort` with `head` or `tail` is a way to achieve equivalent functionality, and indeed, multiple Zed users have reached for that combination on their own and shown us that in their sample Zed at which point we've recognized they could get better performance if they used `top` instead. So in the interest of keeping the language small there's consensus on just optimizing that combination so that it invokes the code currently used for the standalone `top` operator to optimize how it's executed.

Since `top` remains in there but undocumented I'll leave this issue open, but I expect we can eventually morph it into that optimization exercise rather than a docs exercise.

**Comment by philrz** [comment]
`top` operator docs are now present at https://zed.brimdata.io/docs/language/operators/top.
