### ISSUE TITLE
Support http/https locations in zq

### ISSUE THREAD

**Issue by henridf** [brimdata/zed#734]
Add support for http/https-located data to zq, similar to the s3 support added in #704 .

**Comment by marktwallace** [comment]
The approach to s3 support has changed since #704 was merged. In #704, S3 was being read sequentially with a goroutine that set download.Concurrency=1 so the S3 object would be read in order. Since then, the approach in our code to S3 downloader has changed. Now in pkg.s3io.Reader, it uses the "Range" option for the S3 Downloader.Download (which is more like fseek) so we can implement a ReadAt(offset) function for an arbitrary offset into the S3 object.

Because of this change, the abstraction layer is different (I think) than it was when #704 was merged. With the new abstraction, we can treat S3 objects "just like files" and fseek when need.

However, AFAIK, http located data probably must be read sequentially (I'm not certain of this -- is there some way to implement an arbitrary ReadAt(offset) for http?). So, I'm not certain how to fit http into the current code where fseek-like access is assumed for files and for S3.

It would help to know the context for this request. Under what circumstance do we anticipate zq users searching though logs that reside on web servers and are served through http? Are there some typical cases for this kind of search?

**Comment by philrz** [comment]
@marktwallace: This is just one person's take, but I'm assuming that the use cases for this are more small-scale convenience situations rather than mission-critical high-perf ones. For instance, right now the [zq-sample-data](https://github.com/brimsec/zq-sample-data) lives in a GitHub repo, so the workflow for using it as shown in our docs would assume first cloning the repo locally. This is fine since most of our user base is fairly technical and hence likely to know `git` and have it installed. OTOH, being able to directly reference an HTTP/HTTPS URL of such files could be seen as a handy convenience as our tools go more mainstream. This might be true for turning packet captures into Zeek logs as well, especially since lots of examples are web-hosted (our favorite test [wrccdc](https://archive.wrccdc.org/pcaps/) pcaps being one good example, but also lots of the CTF & sample attack pcaps saved out there as training resources). If it required required reading files in their entirety without the benefits of fancy seeking, I think that'd be fine.

**Comment by henridf** [comment]
The use case I had in mind was tutorials, demos, examples, etc with sample data. Being able do do things like `zq "search | analytics" https://brimsecurity.com/samples/example.zng` is more convenient than alternatives. (In a different vein, one inspiration for this was kubectl for which docs and examples extensively use https urls to yaml files).

> However, AFAIK, http served data probably must be read sequentially (I'm not certain of this -- is there some way to implement an arbitrary ReadAt(offset) for http?). 

I'm pretty sure there's no equivalent of a Range option for HTTP.

**Comment by marktwallace** [comment]
Interestingly, I just looked at the http 1.1 spec, and there is a Range specifier:

14.35.2 Range Retrieval Requests ...
Range = "Range" ":" ranges-specifier
A server may ignore the Range header. ...

I have never seen it used, but there it is.

Phil's example use case and yours makes sense to me, if we are OK with http not being a high-performance search option, like S3 is.

**Comment by alfred-landrum** [comment]
I'm with @philrz on this: the intention of this work was to make it possible to run command line zq using an http/https uri, like: `zq https://mydata/foo.zng | ... `. Since bare http/https doesn't generally support seeking, or directory-like listing of files, we don't expect to use http/https locations for more sophisticated cases.

**Comment by philrz** [comment]
@mccanne indicated that he recently added some of the support for this. I'm moving this one to our New Issues column as a reminder for us to discuss prioritizing when we do the work to make it a complete feature.
