### ISSUE TITLE
zq -e=false stops processing when first ts-less record is read

### ISSUE THREAD

**Issue by mikesbrown** [brimdata/zed#979]
Given
```
$ cat footypes.json
{
  "descriptors": {
    "foo_log": [
      {
        "name": "_path",
        "type": "string"
      },
      {
        "name": "ts",
        "type": "time"
      },
      {
        "name": "time_field",
        "type": "time"
      }
    ]
  },
  "rules": [
    {
      "descriptor": "foo_log",
      "name": "_path",
      "value": "foo"
    }
  ]
}
$ cat foo.ndjson
{"_path": "foo", "ts": "0", "time_field": 0}
{"_path": "foo", "ts": "1000"}
{"_path": "foo", "time_field": "2000"}
{"_path": "foo", "ts": "3000", "time_field": 3000}
{"_path": "foo"}
```
`zq -e=false` does not allow for the processing of additional valid records once a record with absent `ts` is seen.

Behavior:
```
$ zq -t -e=false  -i ndjson  -j footypes.json '*' foo.ndjson
foo.ndjson: line 3: invalid json type for ts: non-existent
#0:record[_path:string,ts:time,time_field:time]
0:[foo;0;0;]
0:[foo;1;-;]
```

Expected behavior:
```
foo.ndjson: line 3: invalid json type for ts: non-existent
foo.ndjson: line 5: invalid json type for ts: non-existent
#0:record[_path:string,ts:time,time_field:time]
0:[foo;0;0;]
0:[foo;1;-;]
0:[foo;3;3;]
```

**Comment by philrz** [comment]
I noticed a similar issue with `-e=false` for a field other than `ts`. I could open up a separate issue, but perhaps there's a general/wider problem with `-e=false`, so I'll start this out as a comment. When a developer picks this Issue up, hopefully they can assess and say whether a separate issue is justified.

Specifically, I was working with the `ref_id` field of the Zeek `ntp` log type. It's a `bstring` in the "stock" `types.json` that ships with `zq`, which makes sense because it sometimes contains Zeek strings that may or may not contain hex codes, and sometimes it appears as a string that happens to look like an IP address. An example from the [zq-sample-data](https://github.com/brimsec/zq-sample-data):

```
$ zq -e=false -j ~/work/zq/zeek/types.json -t 'count() by ref_id' ntp.ndjson.gz 
#0:record[ref_id:bstring,count:uint64]
0:[83.162.149.224;28;]
0:[STEP;10;]
0:[INIT;10;]
0:[62.75.236.38;2;]
0:[129.250.35.250;22;]
0:[108.61.229.248;22;]
0:[134.71.246.167;14;]
0:[131.188.3.221;24;]
0:[216.229.4.66;8;]
0:[\\x00\\x00\\x00\\x00;632;]
0:[209.133.217.165;4;]
0:[108.61.73.243;26;]
0:[69.89.207.99;50;]
0:[10.0.0.101;26;]
0:[85.197.153.193;24;]
0:[37.187.18.4;2;]
```

However, let's say a user was aware of this and they wanted to perform a CIDR-match on the ones that look like IPs and disregard the rest. I've made a copy of the "stock" `types.json` with the one difference being changing the type for `ref_id`:

```
$ diff types.json types2.json 
1888c1888
<         "type": "bstring"
---
>         "type": "ip"
```

Despite my attempted use of `-e=false`, `zq` exits after it chokes on the first value it sees, which happens to be one of the values containing hex codes.

```
$ zq -e=false -j ~/work/zq/zeek/types2.json -t 'ref_id =~ 83.162.0.0/16 | count()' ntp.ndjson.gz 
ntp.ndjson.gz: format detection error
	tzng: line 1: strconv.ParseUint: parsing "{\"_path\"": invalid syntax
	zeek: line 1: bad types/fields definition in zeek header
	ndjson: line 1: field "ref_id" (type ip): bad addr value field [92 92 120 48 48 92 92 120 48 48 92 92 120 48 48 92 92 120 48 48]
	zjson: undefined type ID: 0
	zng: zng descriptor out of range
	parquet: auto-detection not supported

$ zq -f text 'cut ref_id | head 1' ntp.ndjson.gz 
\\x00\\x00\\x00\\x00
```

**Comment by nwt** [comment]
#2587 remove the typed NDJSON reader.

**Comment by philrz** [comment]
Revisiting the original example with current `zq` commit 8f7e395, here's a Zed shaper that reflects the spirit of the older JSON typing config that was shown:

```
$ cat footypes.zed 
type foo_log={_path:string,ts:time,time_field:time};
put . = shape(foo_log)

$ cat foo.ndjson 
{"_path": "foo", "ts": "0", "time_field": 0}
{"_path": "foo", "ts": "1000"}
{"_path": "foo", "time_field": "2000"}
{"_path": "foo", "ts": "3000", "time_field": 3000}
{"_path": "foo"}

$ zq -z -I footypes.zed foo.ndjson 
{_path:"foo",ts:1970-01-01T00:00:00Z,time_field:1970-01-01T00:00:00Z} (=foo_log)
{_path:"foo",ts:2169-02-08T23:09:07.419103232Z,time_field:null} (foo_log)
{_path:"foo",ts:null,time_field:2000-01-01T00:00:00Z} (foo_log)
{_path:"foo",ts:1830-11-23T00:50:52.580896768Z,time_field:1970-01-01T00:50:00Z} (foo_log)
{_path:"foo",ts:null,time_field:null} (foo_log)
```

That is, `ts` is no longer treated as a special field, and when the record that lacks it is encountered it's filled in with a `null` value.

Looking at this output did lead me to notice the garbage values that were being created for the string values, so I've opened #2605 to track that.
